language: go
sudo: false
notifications:
  email: false

stages:
  - name: test
  - name: deploy
    if: branch = master OR tag =~ ^[0-9]+[.]{1}[0-9]+

jobs:
  include:
    - stage: test
      go:
        - 1.10.x
        - 1.9.x
      addons:
        sonarcloud:
          organization: "adidas-github"
          token:
            secure: $SONAR_TOKEN
      go_import_path: github.com/adidas/acictl
      before_script:
        - make dep
        - make vendor
      script:
        - make test
      after_success:
        - sonar-scanner

    - stage: deploy
      go: 1.10.x
      go_import_path: github.com/adidas/acictl
      script:
        - make dep
      before_deploy:
        - make release
      deploy:
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file:
            - release/acictl-linux-amd64
            - release/acictl-linux-amd64.sha256
            - release/acictl-darwin-amd64
            - release/acictl-darwin-amd64.sha256
            - release/acictl-freebsd-amd64
            - release/acictl-freebsd-amd64.sha256
            - release/acictl-windows-amd64.exe
            - release/acictl-windows-amd64.exe.sha256
            - release/acictl-linux-386
            - release/acictl-linux-386.sha256
            - release/acictl-darwin-386
            - release/acictl-darwin-386.sha256
            - release/acictl-freebsd-386
            - release/acictl-freebsd-386.sha256
            - release/acictl-windows-386.exe
            - release/acictl-windows-386.exe.sha256
          skip_cleanup: true
          on:
            repo: adidas/acictl
            tags: true

addons:
  ssh_known_hosts: github.com
